CREATE MASTER KEY ENCRYPTION BY
    PASSWORD= 'superpassword#12'

CREATE CERTIFICATE cert1
   WITH SUBJECT = 'Certificate for Admin bd';

CREATE SYMMETRIC KEY SSN_Key_01
    WITH ALGORITHM = AES_256
    ENCRYPTION BY CERTIFICATE cert1;
GO